"""Removed daily quota

Revision ID: a94e817972cc
Revises: 0d328a61b91f
Create Date: 2025-06-17 15:22:13.222708+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a94e817972cc'
down_revision: Union[str, None] = '0d328a61b91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'daily_quota_reset_at')
    op.drop_column('projects', 'total_quota_used')
    op.drop_column('projects', 'daily_quota_used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('daily_quota_used', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('total_quota_used', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('daily_quota_reset_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
