"""add monthly quota and period start fields

Revision ID: 0d8028685089
Revises: 068b47f44d83
Create Date: 2025-06-16 14:22:44.662178+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d8028685089'
down_revision: Union[str, None] = '068b47f44d83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('api_quota_monthly_used', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('projects', sa.Column('api_quota_last_reset', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('subscriptions', sa.Column('current_period_start', sa.DateTime(), nullable=True))

    op.execute("""
        UPDATE subscriptions
        SET current_period_start = CASE
            WHEN interval = 'MONTH' THEN current_period_end - INTERVAL '1 month'
            WHEN interval = 'YEAR' THEN current_period_end - INTERVAL '1 year'
            ELSE current_period_end - INTERVAL '1 month'
        END
        WHERE current_period_start IS NULL
    """)

    # Make current_period_start non-nullable after setting defaults
    op.alter_column('subscriptions', 'current_period_start', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'current_period_start')
    op.drop_column('projects', 'api_quota_last_reset')
    op.drop_column('projects', 'api_quota_monthly_used')
    # ### end Alembic commands ###
