name: Compose Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 9 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file from .env.example
        run: |
          cp .env.example .env

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Run compose test
        run: |
          docker compose --profile run test
      
      - name: Get service names
        id: service_names
        run: |
          SERVICE_NAMES=$(docker compose config --services)
          echo "::set-output name=names::$SERVICE_NAMES"

      - name: Print logs for each service
        run: |
          for service in ${{ steps.service_names.outputs.names }}; do
            echo "Logs for service: $service"
            docker compose logs $service
          done

