name: Compose Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 9 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file from .env.example
        run: |
          cp .env.example .env

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Run compose test
        run: |
          docker compose --profile test up --exit-code-from test


