name: Compose Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 9 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./compose.yml"
          compose-flags: "--profile test --env-file .env.example"
        env:
          SERVER_DB_HOST: "db"
