name: Compose Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 9 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file from .env.example
        run: |
          cp .env.example .env

      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./compose.yml"
          compose-flags: "--profile test"
        env:
          SERVER_DB_HOST: "db"
