name: Compose Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 9 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SERVER_OPENAI_API_KEY: ${{ secrets.SERVER_OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file from .env.example
        run: |
          cp .env.example .env

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Run compose test
        run: |
          docker compose --profile test run test
      
      - name: Get service names
        id: service_names
        run: |
          SERVICE_NAMES=$(docker compose config --services)
          echo "names<<EOF" >> $GITHUB_OUTPUT
          echo "$SERVICE_NAMES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Print logs for each service
        run: |
          echo "${{ steps.service_names.outputs.names }}" | while read -r service; do
            echo "Logs for service: $service"
            docker compose logs "$service"
          done

